--Q1
SELECT MC_ARTWORK.CURRENT_LOC, MC_ARTWORK.EST_VALUE
FROM MC_ARTWORK
INNER JOIN MC_LOCATION 
  ON MC_ARTWORK.CURRENT_LOC = MC_LOCATION.LOCATION_ID
WHERE MC_LOCATION.NAME = 'Gallery A'
  AND MC_ARTWORK.EST_VALUE > 1000000;

